name = "template-assemblyscript-evm-trigger"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "template-assemblyscript-evm-trigger_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template-assemblyscript-evm-trigger.wasm"
command = "npm run build:release"
